name: travelex
description: Travelex - NH accommodates both self-booking and Travel agent driven bookings to give organization a great thrust in servicing their employees..

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  flutter_pretty_dio_logger: ^2.0.3
  flutter_form_bloc: ^0.30.1
  flutter_flavor: ^3.1.1
  line_icons: ^2.0.1
  font_awesome_flutter: ^10.3.0
  chips_choice: ^3.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.5
  tuple: ^2.0.1
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  kiwi: ^4.0.3
  syncfusion_flutter_pdfviewer: ^20.4.44
  privacy_screen: ^0.0.6
  dotted_border: ^2.0.0+3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  image_picker: ^0.8.7+2
  path_provider: ^2.0.14
  aad_oauth: ^0.4.3
  intl: ^0.17.0
  package_info_plus: ^4.0.1
  share_plus: ^4.0.10
  webview_flutter: ^4.2.1
  url_launcher: ^6.1.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  kiwi_generator: ^4.0.3
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/apps/nh/images/splash.png"
  min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner:
  kiwi_generator: ^4.0.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/build-runner/flavour.json
    - assets/build-runner/app-fonts/
    - assets/build-runner/svg/
    - assets/apps/nh/images/
    - assets/apps/nh/pdfs/

  fonts:
    - family: regular
      fonts:
        - asset: assets/build-runner/app-fonts/regular.ttf
    - family: italic
      fonts:
        - asset: assets/build-runner/app-fonts/italic.ttf
    - family: semiBold
      fonts:
        - asset: assets/build-runner/app-fonts/semiBold.ttf
    - family: extraBold
      fonts:
        - asset: assets/build-runner/app-fonts/extraBold.ttf
    - family: bold
      fonts:
        - asset: assets/build-runner/app-fonts/bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
